name: clarity-react CI Pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Setup nodejs
      - uses: actions/setup-node@v1
       with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'

      - name: build dependencies 
        run: yarn

      - name: build project 
        run: |
          rm -rf "./dist"
          yarn run build
	        yarn run copy
      
      
